<a href="https://colab.research.google.com/github/fabingui/hello-world/blob/master/Iris%20Acur%C3%A1cia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# mlp for multiclass classification
from numpy import argmax
from pandas import read_csv
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [0]:
# Carregar o dataset Iris de um repositorio Git
path = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'

In [3]:
#Inicio do pre-processamento
df = read_csv(path, header=None)
print(" Dataset completo: \n", df)

 Dataset completo: 
        0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]


In [4]:
#Separacao de dois conjuntos sendo o primeiro com as caracteristicas e o segundo com alvo (target)
X = df.values[:, :-1]
Y = df.values[:, 4]
print("\n O valor de x e: \n", X)

print("\n valor de y e: \n", Y)

X = X.astype('float32')
# passou todas as strings do alvo para inteiros (0,  1, 2) sao tres saidas
Y = LabelEncoder().fit_transform(Y)
print("\n O valor de y encode e: \n", Y)


 O valor de x e: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4

In [0]:
# Geração dos arquivos de treino, teste e validação
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33)

In [0]:
#Geração do modelo
model = Sequential()
model.add(Dense(10, activation='relu', kernel_initializer='he_normal', input_shape=(4,)))
model.add(Dense(8, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(3, activation='softmax'))

In [0]:
# Compilação do modelo
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [9]:
# Teinamento do modelo
model.fit(X_train, y_train, epochs=500, batch_size=32, verbose=1)

Epoch 1/500
4/4 [==============================] - 0s 2ms/step - loss: 3.9236 - accuracy: 0.0000e+00
Epoch 2/500
4/4 [==============================] - 0s 2ms/step - loss: 3.7052 - accuracy: 0.0000e+00
Epoch 3/500
4/4 [==============================] - 0s 2ms/step - loss: 3.4959 - accuracy: 0.0000e+00
Epoch 4/500
4/4 [==============================] - 0s 2ms/step - loss: 3.2898 - accuracy: 0.0000e+00
Epoch 5/500
4/4 [==============================] - 0s 2ms/step - loss: 3.1063 - accuracy: 0.0000e+00
Epoch 6/500
4/4 [==============================] - 0s 2ms/step - loss: 2.9316 - accuracy: 0.0000e+00
Epoch 7/500
4/4 [==============================] - 0s 3ms/step - loss: 2.7709 - accuracy: 0.0100
Epoch 8/500
4/4 [==============================] - 0s 2ms/step - loss: 2.6202 - accuracy: 0.0300
Epoch 9/500
4/4 [==============================] - 0s 2ms/step - loss: 2.4784 - accuracy: 0.0400
Epoch 10/500
4/4 [==============================] - 0s 2ms/step - loss: 2.3576 - accuracy: 0.0800
Epoch

In [10]:
# Avaliaçao do modelo
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print('Acurácia do modelo: %.3f' % acc)

Acurácia do modelo: 0.960
